{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "E   AssertionError: assert 'FAILED' == 'SUCCEEDED'\n - SUCCEEDED\n + FAILED\n", "test_name": "test_confirm_access_request_is_processed_correctly", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_confirm_when_dynamo_db_item_does_not_exist_an_error_is_raised", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_when_related_pds_records_do_not_exist", "rerun": "0"}, "3": {"status": "FAIL", "message": "E   botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetTraceGraph operation: User: arn:aws:sts::723625676534:assumed-role/AWSReservedSSO_NPA-Developer_2024920324f85a59/RIJH3@hscic.gov.uk is not authorized to perform: xray:GetTraceGraph because no identity-based policy allows the xray:GetTraceGraph action\n", "test_name": "test_when_relationship_is_prn_then_validate_realtionship_is_run", "rerun": "0"}, "4": {"status": "FAIL", "message": "E   botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetTraceGraph operation: User: arn:aws:sts::723625676534:assumed-role/AWSReservedSSO_NPA-Developer_2024920324f85a59/RIJH3@hscic.gov.uk is not authorized to perform: xray:GetTraceGraph because no identity-based policy allows the xray:GetTraceGraph action\n", "test_name": "test_when_relationship_is_not_prn_then_validate_realtionship_is_not_run", "rerun": "0"}}, "suite_name": "test_step_functions/test_process_access_request.py"}}}, "date": "July 16, 2024", "start_time": 1721133917.262719, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "5"}